### PR TITLE
Implement relative path to error SIP validation report

### PR DESCRIPTION
**Pull request by DanielCosme**
Solves: #59

### CODE REVIEW

**Comment by djjuhasz** [comment]
@DanielCosme The "Validate metadata" activity is still returning an absolute path on this branch:
image

JSON output (Tilt):
```
{"Name":"Validate SIP metadata","Message":"Content error: metadata validation has failed: /home/preprocessing/shared/enduro2008167314/extract1349385218/digitized_SIP_extra_dossier/header/metadata.xml:139: element datei: Schemas validity error : Element '{[http://bar.admin.ch/arelda/v4}datei',](http://bar.admin.ch/arelda/v4%7Ddatei',) attribute 'id': '_cQ6sm5CChWVqtqmrWvne0W' is not a valid value of the atomic type '{[http://bar.admin.ch/arelda/v4}idDatei'.\n/home/preprocessing/shared/enduro2008167314/extract1349385218/digitized_SIP_extra_dossier/header/metadata.xml](http://bar.admin.ch/arelda/v4%7DidDatei'./n/home/preprocessing/shared/enduro2008167314/extract1349385218/digitized_SIP_extra_dossier/header/metadata.xml) fails to validate\n"
```

**Comment by djjuhasz** [comment]
Verify SIP Manifest output looks good:
image

**Comment by djjuhasz** [comment]
> @DanielCosme The "Validate metadata" activity is still returning an absolute path on this branch: image
> 
> JSON output (Tilt):
> 
> ```
> {"Name":"Validate SIP metadata","Message":"Content error: metadata validation has failed: /home/preprocessing/shared/enduro2008167314/extract1349385218/digitized_SIP_extra_dossier/header/metadata.xml:139: element datei: Schemas validity error : Element '{[http://bar.admin.ch/arelda/v4}datei',](http://bar.admin.ch/arelda/v4%7Ddatei',) attribute 'id': '_cQ6sm5CChWVqtqmrWvne0W' is not a valid value of the atomic type '{[http://bar.admin.ch/arelda/v4}idDatei'.\n/home/preprocessing/shared/enduro2008167314/extract1349385218/digitized_SIP_extra_dossier/header/metadata.xml](http://bar.admin.ch/arelda/v4%7DidDatei'./n/home/preprocessing/shared/enduro2008167314/extract1349385218/digitized_SIP_extra_dossier/header/metadata.xml) fails to validate\n"
> ```

@DanielCosme oops, nevermind --- I got this branch confused with the "relatives-path" branch in the enduro repo.  Looks okay with this branch:
image

**Review by jraddaoui — APPROVED** [review]
Thanks @DanielCosme, LGTM!

It would be nice to move this to a SIP method `SIP.GetRelPath(path)`, but seeing how the paths come from the manifest and how that activity works, it may be even worst. I think this is okay for a first pass, if we find that we need to get the relatives path more often we can create that method and change how that activity works.

**Comment by DanielCosme** [comment]
@jraddaoui The challenge with these error messages is that every activity does it's own thing. So when creating errors, the formatting and the actual thing that checks for them are to tightly coupled. So I could not find one Nice global way of doing this. Not sure why these activities where implemented like this, but that was the code I was given to work with so I did the least amount of changes I could possible do, to avoid regressions.

**Pull request merged**
